PREFIX rdf: <http://www.w3.org/1999/02/22-rdf-syntax-ns#> 
PREFIX foaf: <http://xmlns.com/foaf/0.1/>
PREFIX sim: <http://www.ifi.uio.no/INF3580/simpsons#>
PREFIX fam: <http://www.ifi.uio.no/INF3580/family#>

CONSTRUCT {
    sim:Homer rdf:type foaf:Person ;
              foaf:name ?name ;
              foaf:knows ?relative .
    
    ?relative a foaf:Person ;
              foaf:name ?relativename .
}
WHERE { 
    {
        sim:Homer foaf:name ?name .

        ?relative fam:isRelativeOf sim:Homer ;
                  foaf:name ?relativename .
    } UNION {
        sim:Homer fam:isRelativeOf ?relative ;
                  foaf:name ?name .

        ?relative foaf:name ?relativename .
    }
}
